### ISSUE TITLE
softethervpn5: ready to merge to 18.06 release?

### ISSUE THREAD

**Issue by lars18th** [Andy2244/openwrt-extra#12]
Hi @Andy2244 ,

Please, can you push to merge the `softethervpn5` to the 18.06 branch?
https://github.com/openwrt/packages/issues/8179

Thank you for craete/maintain this package!

**Comment by Andy2244** [comment]
I decided to not maintain/merge it for 18.x, i will maintain it for 19.x and snapshots. It can still be build/installed against 18.x via my package-builder.

**Comment by lars18th** [comment]
OK. However, 19.x will be released in two or three months!
