### ISSUE TITLE
New package: RR Redir

### ISSUE THREAD

**Issue by lars18th** [Andy2244/openwrt-extra#14]
Hi @Andy2244 

I don't want to take advantage of you. But I see that you have a lot of experience when it comes to making packages for OpenWRT.

I do a request for creating a package for the tool `RR Redir`: https://github.com/openwrt/packages/issues/8202
However, no one has accepted it.

I need to use it for this: My connection uses **two** different proxies. One is Master and another is a Backup. But the SoftEtherVPN doesn't have support for "multiple proxies". So each connection can use just one proxy. So my solution is to use this `rrredir` tool for connecting first to the Master and only if it's unavailable then connect to the Backup. With this solution the "proxy" configured with SoftEtherVPN is the port where the tool is listening.

More or less, is like a "load-balancer". And it works when I run it on my Linux workstation as a test bed. But, I want to include it in my OpenWRT router. So for this reason I need the package.

Can you help me, please?
`RR Redir` it's just a simple binary with no dependencies and plain C code (4 source files, and 2 headers).

**Comment by Andy2244** [comment]
Sure looks pretty trivial, i will have a go. Btw you just need the binary or should this start as a service and if so what are the default usefully start parameters for openwrt?

**Comment by lars18th** [comment]
> Sure looks pretty trivial, i will have a go. Btw you just need the binary or should this start as a service and if so what are the default usefully start parameters for openwrt?

Great!

Regarding the "configuration" as you can see it's a simple binary with parameters. So, different strategies are possible:
1. Only binary package (no init script).
2. Basic init script with SERVICE_PARAMS for the user configuration.
3. Add one `/etc/config/rrredir` file for configure it.

I leave it up at your discretion for the best option. :wink:

**Comment by Andy2244** [comment]
ok done, can you test if it works correctly. I just did a quick qemu test and binary showed the help.

Did also build via my package-builder against snapshots sdk.

PS: Will add config later, need to-do some other stuff.

**Comment by lars18th** [comment]
Hi @Andy2244 ,

I don't have a docker image for package-builder. I only have the openwrt-buildroot image. So I can't compile the package at time to testing it.
Please, can you share some x86_64 or ramips-mt76x8 .ipk ?

Thank you!

**Comment by lars18th** [comment]
Sorry @Andy2244 , I weel see now https://github.com/Andy2244/openwrt-package-builder !

**Comment by lars18th** [comment]
> Sorry @Andy2244 , I weel see now https://github.com/Andy2244/openwrt-package-builder !

Hi @Andy2244 ,
Quite complex to setup in my environment as it isn't a pure docker image. So, please share some binary precompiled package.

**Comment by Andy2244** [comment]
> Quite complex to setup in my environment as it isn't a pure docker image.

What you mean by "isn't a pure docker image"? I don't understand what this means, since my builder is independent, self contained from anything else?

I mean what is your build environment? Do you use the sdk or full buildroot?

**Comment by lars18th** [comment]
Hi @Andy2244 ,

> I mean what is your build environment? Do you use the sdk or full buildroot?

I use a docker image with "all inside the docker image" for compiling the kernel with the buildroot. However, to compile a package I need to recompile all the buid environment just for one small package.

The problem is: I can't execute scripts in the command, I can only instance docker images. This is the reason to comment that your `openwrt-package-builder` is _quite_ complex.

So, to not consume more time: You have some precompiled ipk?

**Comment by Andy2244** [comment]
I still don't know what target version you need, 18.06.x, snapshots?

So you cant just add this feed to your containers `feeds.conf` or `feeds.conf.default` and consume it?

PS: If you have docker already running, all you need is the builder script and a working build config.
```
VERSION="snapshots"
TARGET="ramips"
SUBTARGET="mt76x8"

FEED_1="src-git extra https://github.com/Andy2244/openwrt-extra.git"
FEED_1_PACKAGES="rrredir"

DISABLE_SIGNING=1
```

**Comment by lars18th** [comment]
Hi @Andy2244 ,

Thank you for the tip (about the `config.txt`). However, I still have problems. Please see my issue at https://github.com/Andy2244/openwrt-package-builder/issues/5

In the meantime, can you provide a build of? Please...
```
VERSION="18.06.1"
TARGET="ramips"
SUBTARGET="mt76x8"

FEED_1="src-git extra https://github.com/Andy2244/openwrt-extra.git"
FEED_1_PACKAGES="rrredir"

DISABLE_SIGNING=1
```
and
```
VERSION="18.06.1"
TARGET="x86"
SUBTARGET="64"

FEED_1="src-git extra https://github.com/Andy2244/openwrt-extra.git"
FEED_1_PACKAGES="rrredir"

DISABLE_SIGNING=1
```

Thank you!

**Comment by Andy2244** [comment]
here you go

[rrredir_2018-12-20-ef4eb6ca-1_x86_64.zip](https://github.com/Andy2244/openwrt-extra/files/2910101/rrredir_2018-12-20-ef4eb6ca-1_x86_64.zip)
[rrredir_2018-12-20-ef4eb6ca-1_mipsel_24kc.zip](https://github.com/Andy2244/openwrt-extra/files/2910102/rrredir_2018-12-20-ef4eb6ca-1_mipsel_24kc.zip)

**Comment by lars18th** [comment]
> here you go
> 
> [rrredir_2018-12-20-ef4eb6ca-1_x86_64.zip](https://github.com/Andy2244/openwrt-extra/files/2910101/rrredir_2018-12-20-ef4eb6ca-1_x86_64.zip)
> [rrredir_2018-12-20-ef4eb6ca-1_mipsel_24kc.zip](https://github.com/Andy2244/openwrt-extra/files/2910102/rrredir_2018-12-20-ef4eb6ca-1_mipsel_24kc.zip)

Hi @Andy2244 ,

Tested on both platforms: it works like a charm.
So ready to mainstream.

You will implement some init.d script?

Thank you for your effort! :wink:

**Comment by Andy2244** [comment]
> You will implement some init.d script?

If i have some extra time yes.

**Comment by lars18th** [comment]
> > You will implement some init.d script?
> 
> If i have some extra time yes.

OK. Great! When you can! :tada: 
An thank you for your good support. :+1:

**Comment by lars18th** [comment]
Hi @Andy2244 ,

The tool `rrredir` has been updated with bind address support.
Please, can you update the package to the most recent version?

Thank you!

**Comment by Andy2244** [comment]
ok updated

**Comment by lars18th** [comment]
> ok updated

So, time for a PR to merge it with the Master OpenWRT Packages?

**Comment by Andy2244** [comment]
Need to figure out the service script first. Still working mainly on cifsd, samba4 atm, so maybe next weekend.

**Comment by lars18th** [comment]
> Need to figure out the service script first. Still working mainly on cifsd, samba4 atm, so maybe next weekend.

Hi @Andy2244 ,

OK. Don't worry! You're doing a good job. When you can.
