### ISSUE TITLE
smdb install luci error

### ISSUE THREAD

**Issue by MxCen** [Andy2244/openwrt-extra#19]
/usr/lib/lua/luci/controller/smbd.lua:6: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/smbd.lua:6: in function 't'
	/usr/lib/lua/luci/dispatcher.lua:465: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:188: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by Andy2244** [comment]
I need some more information, how/when did you get this error?

**Comment by MxCen** [comment]
> Sorry,
补充信息如下：
Additional information is as follows:
-----------------------------------------------------------------------------------------
使用来源（source）：
Openwrt：https://github.com/coolsnowwolf/lede
luci：https://github.com/coolsnowwolf/luci
packages：https://github.com/coolsnowwolf/packages
routing：https://git.openwrt.org/feed/routing.git;openwrt-18.06
-----------------------------------------------------------------------------------------
进行编译后，安装
After compiling, install
Prompt the above error，No access to any Luci interface

**Comment by Andy2244** [comment]
Sorry but this is a third party openwrt repo, so i cant really give support for it.
It seems there luci repo is simply outdated, so use the official instead and it should work.

**Comment by MxCen** [comment]
OK, thank you. I'm trying to solve it myself
