### ISSUE TITLE
qemu build error

### ISSUE THREAD

**Issue by phoenixxie0** [Andy2244/openwrt-extra#2]
I use the lede git version source. While building qemu, It has some issue 
make[5]: Leaving directory '/opt/lede/build_dir/hostpkg/qemu-2.11.1/dtc'
ccache gcc -I/opt/lede/build_dir/hostpkg/qemu-2.11.1/util -Iutil -I/opt/lede/build_dir/hostpkg/qemu-2.11.1/tcg -I/opt/lede/build_dir/hostpkg/qemu-2.11.1/tcg/i386 -I/opt/lede/build_dir/hostpkg/qemu-2.11.1/linux-headers -I/opt/lede/build_dir/hostpkg/qemu-2.11.1/linux-headers -I. -I/opt/lede/build_dir/hostpkg/qemu-2.11.1 -I/opt/lede/build_dir/hostpkg/qemu-2.11.1/accel/tcg -I/opt/lede/build_dir/hostpkg/qemu-2.11.1/include -I/opt/lede/build_dir/hostpkg/qemu-2.11.1/dtc/libfdt -pthread -I/opt/lede/staging_dir/hostpkg/include/glib-2.0 -I/opt/lede/staging_dir/hostpkg/lib/glib-2.0/include -m64 -mcx16 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wall -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv  -Wexpansion-to-defined -Wendif-labels -Wno-shift-negative-value -Wno-missing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-declaration -Wold-style-definition -Wtype-limits -I/opt/lede/build_dir/hostpkg/qemu-2.11.1/tests -MMD -MP -MT util/memfd.o -MF util/memfd.d -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -O2 -I/opt/lede/staging_dir/host/include -I/opt/lede/staging_dir/hostpkg/include -I/opt/lede/staging_dir/target-x86_64_musl/host/include  -c -o util/memfd.o util/memfd.c
util/memfd.c:40:12: error: static declaration of 'memfd_create' follows non-static declaration
 static int memfd_create(const char *name, unsigned int flags)
            ^~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/mman-linux.h:115:0,
                 from /usr/include/x86_64-linux-gnu/bits/mman.h:45,
                 from /usr/include/x86_64-linux-gnu/sys/mman.h:41,
                 from /opt/lede/build_dir/hostpkg/qemu-2.11.1/include/sysemu/os-posix.h:29,
                 from /opt/lede/build_dir/hostpkg/qemu-2.11.1/include/qemu/osdep.h:104,
                 from util/memfd.c:28:
/usr/include/x86_64-linux-gnu/bits/mman-shared.h:46:5: note: previous declaration of 'memfd_create' was here
 int memfd_create (const char *__name, unsigned int __flags) __THROW;
     ^~~~~~~~~~~~
/opt/lede/build_dir/hostpkg/qemu-2.11.1/rules.mak:66: recipe for target 'util/memfd.o' failed
make[4]: *** [util/memfd.o] Error 1
make[4]: Leaving directory '/opt/lede/build_dir/hostpkg/qemu-2.11.1'
Makefile:140: recipe for target '/opt/lede/build_dir/hostpkg/qemu-2.11.1/.built' failed
make[3]: *** [/opt/lede/build_dir/hostpkg/qemu-2.11.1/.built] Error 2
make[3]: Leaving directory '/opt/lede/feeds/extra/qemu-userspace'
package/Makefile:107: recipe for target 'package/feeds/extra/qemu-userspace/host/compile' failed
make[2]: *** [package/feeds/extra/qemu-userspace/host/compile] Error 2
make[2]: Leaving directory '/opt/lede'
package/Makefile:103: recipe for target '/opt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/opt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/opt/lede'
/opt/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by rpugsley** [comment]
The problem is in version 2.11.1. Change your Makefile to:

```
include $(TOPDIR)/rules.mk

PKG_NAME:=qemu
PKG_VERSION:=2.12.0
PKG_RELEASE:=

PKG_SOURCE_URL:=https://download.qemu.org/
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz
PKG_HASH:=E69301F361FF65BF5DABD8A19196AEAA5613C1B5AE1678F0823BDF50E7D5C6FC
PKG_LICENSE:=GPL-2.0
```

**Comment by rpugsley** [comment]
Change your feeds/extra/qemu-userspace/Makefile to: 
```
include $(TOPDIR)/rules.mk

PKG_NAME:=qemu
PKG_VERSION:=2.12.0
PKG_RELEASE:=

PKG_SOURCE_URL:=https://download.qemu.org/
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz
PKG_HASH:=e69301f361ff65bf5dabd8a19196aeaa5613c1b5ae1678f0823bdf50e7d5c6fc
PKG_LICENSE:=GPL-2.0
```

**Comment by Andy2244** [comment]
@rpugsley thanks for the fix/info, i did not have much time this months to update/check some issues that did show up, since i did a full recompile/install against master myself.

**Comment by Andy2244** [comment]
@xseven007 should compile now against latest master
