### ISSUE TITLE
samba4-client and samba4-admin missing dependency on libncurses

### ISSUE THREAD

**Issue by monsterzzzz** [Andy2244/openwrt-extra#23]
While compiling samba4-client and samba4-admin, "libncursesw.so.6" is missing, After adding libncurses 
to DEPENDS in Makefile, it works. Please have a check.

**Comment by Andy2244** [comment]
Probably one of those odd optional auto lib dependencies, its not needed and samba4 will build fine without it, yet the waf buildsystem has no option to clearly control the linking/detection behavior and just pulls in some libs it detects.

I can add the same workaround like pam aka `+PACKAGE_libncursesw:libncursesw
`

**Comment by monsterzzzz** [comment]
sounds good

**Comment by monsterzzzz** [comment]
After updating ncurses to the latest version https://github.com/openwrt/openwrt/tree/master/package/libs/ncurses ,everything seems to work.
