### ISSUE TITLE
ksmbd service not working on freshly installed image

### ISSUE THREAD

**Issue by sirinsidiator** [Andy2244/openwrt-extra#25]
I've recently installed a fresh copy of OpenWrt 19.07.3 (r11063-85e04e9f46) downloaded from the link provided [on this page](https://openwrt.org/toh/tp-link/tl-wdr3600) on my old TP-Link WDR3600 router.
Afterwards I installed "luci-app-ksmbd" via the webinterface, configured it to listen to the lan interface and added a share. The luci interface shows the following versions when I click on Services > Network Shares:
>Ksmbd: 3.2.6 Kmod: 3.1.3

The resulting /etc/ksmbd/smb.conf file looks like this:
```
[global]
        netbios name = OpenWrt
        server string = Shelf
        workgroup = WORKGROUP
        interfaces = br-lan
        bind interfaces only = yes
        ipc timeout = 20
        deadtime = 15
        map to guest = Bad User
        smb2 max read = 64K
        smb2 max write = 64K
        smb2 max trans = 64K
        cache read buffers = no
        cache trans buffers = no

######### Dynamic written config options #########

[shelf]
        path = /mnt/sda1
        valid users = root
        create mask = 0666
        directory mask = 0777
        read only = no
        guest ok = yes
```

I even followed the recommendation in [this guide](https://openwrt.org/docs/guide-user/services/nas/cifs.server) and set up firewall rules to explicitly allow the necessary ports for the lan interface.

The process is running, but it's not listening to any ports:
```
root@OpenWrt:~# ps|grep ksmbd
 2058 root      1224 S    /usr/sbin/ksmbd.mountd --n
 2059 root      1392 S    /usr/sbin/ksmbd.mountd --n
 2218 root      1212 S    grep ksmbd
root@OpenWrt:~# netstat -tulpn|grep ksmbd
```

All I see in the system log is this error whenever I reboot or restart the service:
> kern.err kernel: [  228.873029] ksmbd: ksmbd_tcp_set_interfaces:596: Unknown interface:

I've tried to remove the "interfaces" and "bind interfaces only" entry form the config template to no effect. Reinstalling the package also doesn't change anything and I can't count how many times I've rebooted the router.

After extensive googling I found #24 which seems to describe the same problem (although I didn't get any errors during installation). Reading the linked thread it seems they got it working by manually compiling the package for their router, but before I spend hours to try to set up a linux environment just so I can build the package myself, I would like to ask if there is something else I can try? I would expect a package which is installed via the package manager on a newly installed system to work without any problem.

**Comment by Andy2244** [comment]
> I would expect a package which is installed via the package manager on a newly installed system to work without any problem.

Yes, i assume the issue is this https://github.com/openwrt/packages/pull/12502
This means you use the older 3.1.3 kernel mod with the newer 3.2.6 userspace tools, which are incompatible.

I guess your use-case shows that i should really revert this PR, until we have a solid solution for such a case. 

Sorry for the inconvenience.

**Comment by Andy2244** [comment]
If the revert PR is merged the buildbots will pickup the change in ~12-24 hours and the old compatible package will be up again, than you can reinstall.

**Comment by sirinsidiator** [comment]
Thanks for the quick help. Will look into that tomorrow then and let you know if it worked.

**Comment by sirinsidiator** [comment]
It doesn't look like the update is available yet? The package manager still has the old version (Sat Jun 20 12:47:52 2020) as seen [here](https://downloads.openwrt.org/releases/19.07.3/packages/mips_24kc/packages/).

**Comment by Andy2244** [comment]
Yeah the buildbots need to get to your target, some other targets have the old version again.
https://downloads.openwrt.org/releases/19.07.3/packages/mips_mips32/packages/

**Comment by sirinsidiator** [comment]
I just reinstalled the package via the webinterface and the error is now gone, but it still doesn't work. I've done a clean install (uninstalled, removed /etc/ksmbd and /etc/config/ksmbd + rebooted before installing again), but even with the default config it doesn't work.

Version is now Ksmbd: 3.2.1 Kmod: 3.1.3
```
root@OpenWrt:~# ps|grep ksmbd
 2047 root      1224 S    /usr/sbin/ksmbd.mountd --n
 2048 root      1392 S    /usr/sbin/ksmbd.mountd --n
 2049 root         0 SW   [ksmbd-br-lan]
 2088 root      1212 S    grep ksmbd
root@OpenWrt:~# netstat -tulpn|grep ksmbd
root@OpenWrt:~# 
```
Is there some verbose mode or log for ksmbd which could give me a clue as to what is going on?

**Comment by Andy2244** [comment]
You can kill the `ksmbd.mountd` and than manually start the userspace service again, i think there is a verbose option.

Also what exactly does not work? Did you try reach the share directly via the router ip + sharename ?

**Comment by sirinsidiator** [comment]
That worked. It seems windows cannot connect to `\\<ip>` before connecting to `\\<ip>\<share>` directly and will simply show an error "The network name cannot be found" in that case, but that's something I can live with.
Thanks again for your help!

**Comment by Andy2244** [comment]
> "The network name cannot be found" in that case, but that's something I can live with.

Install the `wsdd2` package as well and you can just browse the shares via windows explorer/network.

**Comment by sirinsidiator** [comment]
Tried that just now, but it doesn't seem to work. Still getting the error even after rebooting the router.
