### ISSUE TITLE
library conflict 

### ISSUE THREAD

**Issue by kambic** [Andy2244/openwrt-extra#3]
Installing samba4 (4.8.1-1) to root...
Installing krb5-libs (1.16-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/arm_cortex-a9_vfpv3/packages/krb5-libs_1.16-1_arm_cortex-a9_vfpv3.ipk
Collected errors:
 * check_data_file_clashes: Package krb5-libs wants to install file /usr/lib/libcom_err.so
	But that file is already provided by package  * libcomerr
 * opkg_install_cmd: Cannot install package samba4.

i used  --force-overwrite 

opkg install  --force-overwrite samba4_4.8.1-1_arm_cortex-a9_vfpv3.ipk

**Comment by Andy2244** [comment]
The krb5 change was just merged so you need to compile against the latest master, since openwrt-18.06 still has the old version. Did you follow the install steps from the readme and updated the krb5 package to the one in this feed?

**Comment by Andy2244** [comment]
closing this, this feed is designed to work against master for now, not 17.01.
