### ISSUE TITLE
Package samba4 is missing dependencies for the following libraries: libjansson.so.4

### ISSUE THREAD

**Issue by phoenixxie0** [Andy2244/openwrt-extra#4]
There is the log :
`install -d -m0755 /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-x86_64/samba4/usr
if [ -d /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-install/usr/bin ]; then cp -fpR /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-install/usr/bin /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-x86_64/samba4/usr/; fi
if [ -d /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-install/usr/sbin ]; then cp -fpR /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-install/usr/sbin /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-x86_64/samba4/usr/; fi
# install init, config
install -d -m0755 /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-x86_64/samba4/etc/config /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-x86_64/samba4/etc/samba /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-x86_64/samba4/etc/init.d
install -m0644 ./files/samba.config /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-x86_64/samba4/etc/config/samba4
install -m0644 ./files/smb.conf.template /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-x86_64/samba4/etc/samba
install -m0755 ./files/samba.init /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-x86_64/samba4/etc/init.d/samba4
find /opt/lede/build_dir/target-x86_64_musl/samba-4.8.2/ipkg-x86_64/samba4 -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package samba4 is missing dependencies for the following libraries:
libjansson.so.4
Makefile:297: recipe for target '/opt/lede/bin/packages/x86_64/extra/samba4_4.8.2-1_x86_64.ipk' failed
make[3]: *** [/opt/lede/bin/packages/x86_64/extra/samba4_4.8.2-1_x86_64.ipk] Error 1
make[3]: Leaving directory '/opt/lede/feeds/extra/samba4'
Command exited with non-zero status 2
time: package/feeds/extra/samba4/compile#467.66#109.58#591.83
package/Makefile:107: recipe for target 'package/feeds/extra/samba4/compile' failed
make[2]: *** [package/feeds/extra/samba4/compile] Error 2
make[2]: Leaving directory '/opt/lede'
package/Makefile:103: recipe for target '/opt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/opt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/opt/lede'
/opt/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2`

That I has already choose the  libjansson pakage..

**Comment by Andy2244** [comment]
oki thanks, will try reproduce this via x86 target, never seen this dependency so far on other targets.

Going by the docs its only needed for optional Audit logging, wonder why its required on your build?
https://wiki.samba.org/index.php/Package_Dependencies_Required_to_Build_Samba

If not already done, maybe try just selecting the server, without netbios/vfs/ad-dc.

**Comment by phoenixxie0** [comment]
I found that I choose the uwsgi-cgi-luci-support. The uwsgi depend jansson...
[https://github.com/openwrt/packages/commit/e4917a9bc6fe470a9e094109084e6bea9ad55b12](url)

**Comment by phoenixxie0** [comment]
And I also found that in this page, [https://www.freshports.org/net/samba48/](url) , I see there is 
Build dependencies: jansson>=2.10 : devel/jansson

**Comment by Andy2244** [comment]
yeah samba4 is always a bit odd, in that it tries to pull in all possible dependencies if it finds a dev package on the host compiling machine. I would assume that uwsgi-cgi-luci-support installs the dev-headers and samba than adds this dependency.

I will check waf again and see if i can disable this behavior somehow, otherwise i guess i will just add a condition for uwsgi-cgi-luci-support.

Thanks for the report.

PS: Does it compil/install if you add the +jansson dep in the makefile?

**Comment by phoenixxie0** [comment]
After add the +jansson dep in the samba4 makefile. It compilted.

**Comment by Andy2244** [comment]
@xseven007 ok, added the dependency by default, since its just 20kb and dynamically checking for the existence of the headers files on the host seems overkill.
