### ISSUE TITLE
ERROR: System library com_err of version 0.0.0 not found while building using the lede sdk 17.01.2

### ISSUE THREAD

**Issue by silent-x** [Andy2244/openwrt-extra#9]
The sdk is lede-sdk-17.01.2-x86-64_gcc-5.4.0_musl-1.1.16.Linux-x86_64.

**Comment by Andy2244** [comment]
@silent-x Yes, you need the 18.06/snapshot sdk's at least or use the git master/18.06.x branch.

PS: If you try to backport it for 17.01 you need to get the updated krb5/e2fsprogs/libtirpc packages from at least 18.06.

**Comment by silent-x** [comment]
@Andy2244 Thanks! It's working under the 18.06 sdk.
